function b = DAE_B_funs(F,d1,d2,d3,g,m1,m2,m3,m4,theta1,theta2,theta3,theta1_dot,theta2_dot,theta3_dot,x1_dot)
%DAE_B_funs
%    B = DAE_B_funs(F,D1,D2,D3,G,M1,M2,M3,M4,THETA1,THETA2,THETA3,THETA1_DOT,THETA2_DOT,THETA3_DOT,X1_DOT)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    02-Dec-2024 20:57:51

t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = sin(theta2);
t6 = theta1_dot.^2;
t7 = theta2_dot.^2;
t8 = theta3_dot.^2;
t9 = d1.*t2.*t6;
t10 = d2.*t3.*t7;
t11 = d1.*t4.*t6;
t12 = d2.*t5.*t7;
t13 = -t9;
t14 = -t10;
b = [-F;g.*m1;0.0;g.*m2;0.0;0.0;g.*m3;0.0;0.0;g.*m4;0.0;t11;t13;t11+t12;t13+t14;t11+t12+d3.*t8.*sin(theta3);t13+t14-d3.*t8.*cos(theta3);x1_dot.^2.*-2.0;0.0];
end
