function b = DAE_B_funs_1(F,c,d1,d2,d3,g,m1,m2,m3,m4,theta1,theta2,theta3,theta1_dot,theta2_dot,theta3_dot)
%DAE_B_funs_1
%    B = DAE_B_funs_1(F,C,D1,D2,D3,G,M1,M2,M3,M4,THETA1,THETA2,THETA3,THETA1_DOT,THETA2_DOT,THETA3_DOT)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Dec-2024 00:37:12

t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = sin(theta2);
t6 = theta1_dot.^2;
t7 = theta2_dot.^2;
t8 = theta3_dot.^2;
t9 = d1.*t2.*t6.*2.0;
t10 = d1.*t4.*t6.*2.0;
t11 = -t9;
b = [-F;g.*m1;0.0;g.*m2;c.*theta1_dot;0.0;g.*m3;c.*theta2_dot;0.0;g.*m4;c.*theta3_dot;d1.*t4.*t6;-d1.*t2.*t6;t10+d2.*t5.*t7;t11-d2.*t3.*t7;t10+d3.*t8.*sin(theta3)+d2.*t5.*t7.*2.0;t11-d3.*t8.*cos(theta3)-d2.*t3.*t7.*2.0;0.0;0.0];
end
